name: Semgrep
on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
    paths:
      - .github/workflows/semgrep.yml
  # schedule:
    # random HH:MM to avoid a load spike on GitHub Actions at 00:00
    # - cron: '7 18 * * *'
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v3
      - name: Run Semgrep CI
        run: semgrep ci --semgrep-repo-display-name=grepJuice
      - name: Run Curl Commands
        run: |
          curl -X POST https://semgrep.dev/api/v1/deployments/algrep_incorporated/projects/grepJuice/tags \
            -H "Content-Type: application/json" \
            --header 'Authorization: Bearer ${{ secrets.SEMGREP_APP_TOKEN }} \
            -d '{"tags": [ "release1234" ]}'
          curl --location 'https://semgrep.dev/api/sca/deployments/$DEPLOYMENT_ID/sbom_async' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ secrets.SEMGREP_APP_TOKEN }}' \
          --data '{
              "repositoryId": $REPO_ID,
              "formatVersion": {
                  "format": "SBOM_FORMAT_CYCLONEDX",
                  "version": "1.4"
              },
              "metadataComponentType": "SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_APPLICATION",
              "sbomOutputFormat": "SBOM_OUTPUT_FORMAT_JSON",
          }'
